web: bash start.sh
release: mkdir -p bootstrap/cache storage/framework/cache storage/framework/sessions storage/framework/views storage/logs && php artisan key:generate --force || true && php artisan migrate --force && php artisan db:seed --force && php artisan l5-swagger:generate || true

